### ISSUE TITLE
"ExtMetadata" directory fails validation

### ISSUE THREAD

**Issue by openfirmware** [opengeospatial/ets-cdb10#13]
Test says the `ExtMetadata` directory in the root of a CDB is not allowed — I will check the spec to see if this is a test suite issue or a CDB version mismatch.

**Comment by openfirmware** [comment]
@sarasaeedi, are you familiar with the usage of the `ExtMetadata` directory in the root of a CDB? I cannot find any reference to allowing for this directory in OGC CDB 1.0 or OGC CDB 1.1.

**Comment by ghobona** [comment]
@sarasaeedi To check with the CDB SWG whether unexpected folders or files should be ignored or whether they should result in a test failure.

**Comment by ghobona** [comment]
@sarasaeedi has sent out an e-mail to the SWG on 2020-07-08.

**Comment by ghobona** [comment]
Discussion on 2020-07-22 with @DavidFLOR

@DavidFLOR to check with the SWG whether the presence of extra files should/not fail the test.

**Comment by ghobona** [comment]
See notes on the discussion by the SWG in the Comment https://github.com/opengeospatial/ets-cdb10/issues/23#issuecomment-663138190

**Comment by openfirmware** [comment]
Discussion on 2020-08-12: Confirmation from David that `ExtMetadata` directory presence should not fail the test suite. @openfirmware will check to see where the test suite needs to be updated to allow this.

**Comment by ghobona** [comment]
2020-08-26 team meeting

@openfirmware recommended that `ExtMetadata` be added to the allowed list of directories.

@openfirmware to add `ExtMetadata` to the allowed list of directories.
