### ISSUE TITLE
XML files are failing validation

### ISSUE THREAD

**Issue by openfirmware** [opengeospatial/ets-cdb10#19]
In a recent test with a real CDB dataset on version 0.4 of the ETS, multiple XML files are failing basic XML validation. Example:

`Errors: cvc-elt.1.a: Cannot find the declaration of element 'Vector_Attributes'`

These errors should not be happening as the files are reported to be correctly formed.

This looks like a XML schema validation problem in the test suite. I will investigate.

**Comment by openfirmware** [comment]
Here is a summary of differences between the failing files in the Sample CDB, and the passing files in the test CDB embedded in the ETS.

* In the ETS, some XML use schema from opengis.net and others from CDB-Spec.org
* ETS uses ^M line endings (DOS/Windows)
    * This should not have any negative effects
* Files only in ETS:
    * `CMT_Example.xml`
    * `Configuration.xml`
    * `Lights_Client.xml`
    * `xs3p.xsl`
* Files only in Sample:
    * `Geomatics_Attributes.xsl`
    * `Vendor_Attributes.xsl`
* ETS has more datasets defined in Datasets.xml
* `Geomatics_Attributes.xml`:
    * ETS has encoding
    * Sample uses `Vector_Attributes` element, ETS uses `Geomatics_Attributes` element
    * Sample uses opengis.net for schema, ETS uses CDB-Spec.org
    * Sample has useful data, ETS has dummy data
* `Base_Material_Table.xsd`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
    * Sample uses version 3.2, ETS uses version 1.0
* `Composite_Material_Table.xml`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
    * Sample uses version 3.2, ETS uses version 1.0
* `Configuration.xsd`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
* `DIS_Country_Codes.xsd`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
* `Defaults.xsd`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
* `Feature_Data_Dictionary.xsd`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
* `Geomatics_Attributes.xsd`:
    * Sample: "UTF-8", ETS: "utf-8"
    * ETS has a stylesheet
    * Sample uses CDB-Spec.org, ETS uses opengis.net
    * Sample uses version 1.2, ETS uses version 3.2
* `Lights.xml`:
    * Sample uses version 3.2, ETS use version 1.0
    * Sample uses CDB-Spec.org, ETS uses opengis.net
* `Model_Components.xsd`:
    * Sample uses version 3.2, ETS use version 1.0
* `Model_Metadata.xsd`:
    * Sample uses version 3.2, ETS use version 1.0
* `Moving_Model_Codes.xsd`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
* `OpenFlight_Model_Extensions.xsd`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
    * Sample uses version 3.2.1, ETS use version 1.0
* `Vector_Attributes.xsd`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
    * Sample uses version 1.2, ETS uses version 1.0
* `Vendor_Attributes.xsd`:
    * Sample: "UTF-8", ETS: "utf-8"
    * ETS has a stylesheet
    * Sample uses CDB-Spec.org, ETS uses opengis.net
    * Sample uses version 1.2, ETS uses version 3.2
* `Version.xsd`:
    * Sample uses CDB-Spec.org, ETS uses opengis.net
    * Sample uses version 3.2.1, ETS use version 1.0
* `Vendor_Attributes.xml`:
    * ETS has encoding
    * Sample uses `Vector_Attributes` element, ETS uses `Vendor_Attributes`
    * Sample uses opengis.net, ETS uses CDB-Spec.org
* `Version.xml`:
    * Sample uses XMLSchema (from w3.org), ETS uses opengis.net

REPLACING the `Metadata/Schema` directory in the failing CDB with the `Metadata/Schema` directory from the passing CDB makes the Sample CDB pass, so this seems to be the source of the test failures. We need to determine if the test is actually failing against the specification, or if the ETS is too strict on applying the schema files.

In the case of the former, then maybe the ETS should print better warnings regarding schema file differences. In the latter case, the ETS needs to be updated to support more flexible schema definitions.

Questions:

* Is there a recommendation for opengis.net vs CDB-Spec.org as the definitive source?
* For "utf-8" vs "UTF-8" in the XML elements?
* For "1.0" vs "3.2" in the schema element definitions?

Can you comment on any of these, @sarasaeedi ?

**Comment by openfirmware** [comment]
The issue with these files validation is in the CDB being tested, as the Metadata XML files are using XML namespaces referring to `opengis.net` but the *Schema* files in the CDB refer to `CDB-Spec.org`. The test suite validates the Metadata XML files against the XSD schema files *in the CDB filesystem*, and the test suite *does not* read the XML file to lookup the schema file.

What should the test suite do? Should it use the schema files in the CDB regardless of what is in the XML Metadata files, or should the test suite download the remote schema file if possible?

**Comment by openfirmware** [comment]
I improved the error message for XML validation errors in cda789527a29f2b822faf083a153e70372e15315. It now says that the XML is invalid according to the schema, even if the XML is "well-formed".

**Comment by ghobona** [comment]
Team discussion on 2020-07-02 confirmed that this issue is solved.

The solution led to the discovery of a separate Vendor Attributes problem which shall be logged in a separate GitHub issue.
