### ISSUE TITLE
List of implemented tests and requirements

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-cdb10#23]
https://docs.google.com/spreadsheets/d/1xQoAjQ7486JjTulHI5pRYHky0KkxUTGurPBs775dQR8/edit#gid=0

**Comment by ghobona** [comment]
Agreement during 2020-07-08 call to invite someone from SWG to help identify which tests are mandatory for a PASS result.

**Comment by ghobona** [comment]
@sarasaeedi has sent out an e-mail to the SWG on 2020-07-08.

**Comment by ghobona** [comment]
@sarasaeedi To add an additional column in the spreadsheet to identify which tests have been implemented.

**Comment by ghobona** [comment]
Discussion on 2020-07-22.

CDB is designed to be used for different contexts by different users.

Use cases may require different requirements to be implemented.

The ETS has turned out to be not something that most implementors can use in its current form because of not testing content.

If you do not test the content, then it's difficult to determine whether the CDB is valid.

Action: @sarasaeedi to update the spreadsheet.

Action: @DavidFLOR to start socialise the ETS with the SWG.

**Comment by DavidFLOR** [comment]
An initial discussion was begun in the CDB SWG meeting on 23 July.  SWG participants were asked to review Sara's spreadsheet; as well as this Github repo; and references to CITE testing implementations for other standards (WFS 2.0 and Geopackage as exemplars of different approaches); and to prepare for some kind of consensus-finding effort in the SWG

**Comment by ghobona** [comment]
One possible solution that has been identified in the SWG is to define one core and a set of different profiles. Perhaps this could be done as a Corrigendum to CDB 1.0 and CDB 1.1.

CDB 1.2 should be developed to include this information.

**Comment by ghobona** [comment]
2020-08-12.

As discussed in the team meeting, the tests currently implemented in this test suite are to be all considered mandatory.

**Comment by ghobona** [comment]
2020-08-26

@sarasaeedi To convert the list of implemented and non-implemented requirements to a table in a Markdown file. Then the markdown file will be placed in [site folder](https://github.com/opengeospatial/ets-cdb10/tree/master/src/site/markdown) and referenced from `index.md`.

**Comment by sarasaeedi** [comment]
I will add why some of the tests are not available (e.g. visuals, etc.)

**Comment by ghobona** [comment]
Fixed by PR https://github.com/opengeospatial/ets-cdb10/pull/30
