### ISSUE TITLE
TEAM Engine installation clarification

### ISSUE THREAD

**Issue by openfirmware** [opengeospatial/ets-cdb10#27]
In the guide for ["How to Deploy to TEAM Engine"](https://github.com/opengeospatial/ets-cdb10/blob/master/src/site/markdown/how_to_team_engine.md#install-ets-cdb10), one of the steps says to "install the CDB10 ETS dependencies… into the TEAM Engine library directory (TE_BASE/lib)." When I did this, I ran into unusual errors running the test suite in TEAM Engine.

Instead, I tried installing the dependencies into the `WEB-INF/lib` directory for TEAM Engine and it works. The documentation needs to be updated to match whichever is the correct method.

**Comment by ghobona** [comment]
I agree. Both the `target/ets-cdb10-0.5-SNAPSHOT-ctl.zip` and `target/ets-cdb10-0.5-SNAPSHOT-deps.zip` instructions need updating.

Here's how I described the WFS instructions in my personal notes.

From `/Github/ets-wfs20/target`, unpackage `ets-wfs20-1.33-SNAPSHOT-ctl.zip` and copy the ‘wfs’ folder to `/home/ogccite/teamengine/scripts`

From `/Github/ets-wfs20/target`, unpackage `ets-wfs20-1.33-SNAPSHOT-deps.zip`. Then copy all of the jar files to `/tomcat/webapps/teamengine/WEB-INF/lib`.

Now copy the contents of the file `/home/ogccite/teamengine/scripts/wfs/2.0.0/config.xml` into the file `/home/ogccite/teamengine/config.xml` (place them as an additional `/config/scripts/organisation/standard` element i.e. there should be only one `organisation` in the script)

**Comment by openfirmware** [comment]
Documentation should also clarify to extract the ZIP contents into the `WEB-INF/lib`.

**Comment by ghobona** [comment]
Fixed with Commit https://github.com/opengeospatial/ets-cdb10/commit/49f152b6d333fe1faa0ce3a95e016cb3f82d1660 and https://github.com/opengeospatial/ets-cdb10/commit/41a5692d934284fa5b77bcc4f5fe07cbc9124dde
