### ISSUE TITLE
Configure the CDB Structure conformance class to be the minimal required for certification

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cdb10#39]
`CDB Structure` shall be configured as Basic Conformance Class.

**Comment by dstenger** [comment]
@keshav-nangare Can you please make sure that the new HTML report is working correctly and that `CDB Structure` is considered as basic conformance class?

**Comment by keshav-nangare** [comment]
@dstenger 

I have executed the test suite successfully on my machine and `CDB Structure` is considered as a basic conformance class. Also, the generation of a new HTML report is working fine.

**Comment by dstenger** [comment]
@keshav-nangare Beta environment (https://cite.opengeospatial.org/te2/) was updated but the Basic Conformance Classes are not displayed in the HTML report. Can you please check this problem?

**Comment by keshav-nangare** [comment]
Fixed with #47 PR.
