### ISSUE TITLE
Validate file extensions

### ISSUE THREAD

**Issue by openfirmware** [opengeospatial/ets-cdb10#4]
The file extensions for files should be validated as conforming to the types allowed for their enclosing dataset; e.g. "TIFF" files for Elevation.

I need to review the OGC CDB Core Standard and find the exact allowed types before writing these tests.

**Comment by openfirmware** [comment]
In OGC CDB 1.1, there are no restrictions on the file name extensions permitted based on the Dataset. Is this test still necessary?

**Comment by ghobona** [comment]
Team confirmed (on 2020-07-02) collective understanding that for CDB 1.0, there are no restrictions on file types that can be expected in a CDB dataset.
