### ISSUE TITLE
Validate GSModel zip archives

### ISSUE THREAD

**Issue by openfirmware** [opengeospatial/ets-cdb10#6]
The following files can reside in ZIP archives:

1. GSModelGeometry
2. GSModelTexture
3. GSModelMaterial
4. GSModelDescriptor
5. GSModelInteriorGeometry
6. GSModelInteriorTexture
7. GSModelInteriorMaterial
8. GSModelInteriorDescriptor

ZIP archives should be inspected and validated.

**Comment by openfirmware** [comment]
Relevant sections from Volume 1, OGC CDB 1.0:

* Annex A.1.13 Geospecific Model (GSModel) Storage
* Annex A.1.17 Archive Names
* Section 3.6.3.2 File Naming Convention for Files in ZIP Archives
* Section 5.8.1 Tiled GSModel Datasets

**Comment by openfirmware** [comment]
I noticed that `OGC 15-113r3, A.1.13, Test 72` has the same "test purpose" text as `OGC 15-113r3, A.1.13, Test 69`.

It says:

> Verify that the files from the GSModelGeometry and GSModelInteriorGeometry datasets have the following naming convention: LatLon_Dnnn_Snnn_Tnnn_LOD_Un_Rn_FC_FSC_MODL.flt

But should probably say:

> Verify that the files from the GSModelDescriptor and GSModelInteriorDescriptor datasets have the following naming convention: LatLon_Dnnn_Snnn_Tnnn_LOD_Un_Rn_FC_FSC_MODL.xml

This did not get changed with OGC CDB 1.1 (OGC 15-113r5). It should not affect the completion of this task, but may be something implementors may run into.

**Comment by ghobona** [comment]
2020-10-01

@openfirmware To look into the GSModel test results from Jeremie and the associated CDB tree.
