### ISSUE TITLE
Improve TEAM Engine Compatibility

### ISSUE THREAD

**Issue by openfirmware** [opengeospatial/ets-cdb10#7]
When running a local installation of TEAM Engine, ets-cdb10 test results on a CDB kept on the local filesystem will produce a test report that is not parsed by TEAM Engine. Because it is not parsed, you must manually view the test results to see which tests passed/failed.

I will check out other ETS repositories to see how this is done properly.

**Comment by openfirmware** [comment]
I'm comparing the CTL script from this repository to [the one in ETS Security Client 1.0](https://github.com/opengeospatial/ets-security-client10/blob/master/src/main/scripts/ctl/security-client10-suite.ctl), a repo I have been working on this past year. I haven't found any major differences that would cause the CDB ETS to not support the new HTML output type…

**Comment by dstenger** [comment]
@openfirmware 
Thank you for the good work.
What is the current status of this issue? So, the TestNG report can be viewed via TEAM Engine but the HTML report is not generated? Does this problem still occur?

**Comment by ghobona** [comment]
Team decision on 2020-07-02 for @keshav-nangare to review the issue and advise @openfirmware

**Comment by keshav-nangare** [comment]
@ghobona 

I have fixed TeamEngine new HTML report generation issue and also added support for local resource file upload in CTL form. We can see the new field in below screenshot: 
![image](https://user-images.githubusercontent.com/14732650/87007289-a34fb880-c1df-11ea-94ac-ce465605a0ad.png)

@openfirmware 
Can you please check the reported issue still exists?

**Comment by ghobona** [comment]
Thanks @keshav-nangare

**Comment by openfirmware** [comment]
I set up TEAM Engine 5.4 with Tomcat 7 and Oracle JDK 1.8. I tested with the path to the CDB included as a sample in this ETS using the IUT of `file:///Users/jpbadger/src/team/ets-cdb10/src/test/resources/CDB` and the output now properly displays in the browser.

There are errors associated with using this IUT, but they are not due to the pull request.

**Comment by ghobona** [comment]
Pull Request https://github.com/opengeospatial/ets-cdb10/pull/25 created.

**Comment by openfirmware** [comment]
Fixed with merge of #25.
