### ISSUE TITLE
Validating schema files (Metadata folder) from CDB 1.1

### ISSUE THREAD

**Issue by sarasaeedi** [opengeospatial/ets-cdb10#9]
Validating the new .xsd schema files which are located in Metadata folder and recently approved in CDB 1.1

**Comment by openfirmware** [comment]
Do we have a reference CDB 1.1 we can test?

Currently the Metadata tests will automatically look for the bundled `xsd` files in the CDB for validating schema, so if the bundled CDB has the proper files then it *should* pass regardless of version.

**Comment by ghobona** [comment]
Team decision to focus on CDB 1.0 for the current Q3 2020 window.
